#spring:
#  application:
#    name: homepage-eureka
#
#server:
#  port: 8000
#
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
